services:
  # ---------- Persistence ----------
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: doc_db
    environment:
      POSTGRES_USER: ${DB_USER:-doc}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-doc}
      POSTGRES_DB: ${DB_NAME:-docdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-doc} -d ${DB_NAME:-docdb}"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio:
    image: minio/minio
    container_name: doc_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console UI
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7
    container_name: doc_redis
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # ---------- Model Runtime ----------
  ollama:
    image: ollama/ollama
    container_name: doc_ollama
    ports:
      - "11434:11434"
    volumes:
      - models:/root/.ollama
    environment:
      OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE:-4h}
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 10s
      timeout: 5s
      retries: 30

  # ---------- Application Services ----------
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: doc_app
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      # Database
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-doc}
      DB_PASSWORD: ${DB_PASSWORD:-doc}
      DB_NAME: ${DB_NAME:-docdb}
      # Object storage (MinIO S3)
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minio}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minio123}
      S3_BUCKET: ${S3_BUCKET:-doc-bucket}
      S3_REGION: ${S3_REGION:-us-east-1}
      # Redis
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      # Models - Ollama LLMs
      OLLAMA_BASE: ${OLLAMA_BASE:-http://ollama:11434}
      TEXT_LLM_MODEL: ${TEXT_LLM_MODEL:-qwen2.5:7b-instruct-q4_K_M}
      VLM_MODEL: ${VLM_MODEL:-qwen2-vl:7b-instruct-q4_K_M}
      # Embedder (local in-process)
      EMBEDDER_PROVIDER: ${EMBEDDER_PROVIDER:-local}
      EMBEDDER_MODEL: ${EMBEDDER_MODEL:-BAAI/bge-small-en-v1.5}
      EMBEDDER_DEVICE: ${EMBEDDER_DEVICE:-mps}
      EMBEDDER_NORMALIZE: ${EMBEDDER_NORMALIZE:-True}
      # Application settings
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
    volumes:
      - ./src:/app:cached                      # dev bind mount for code
      - data:/data                             # inputs/outputs
      - models:/root/.cache/huggingface        # share HF cache
    ports:
      - "${APP_PORT:-8080}:8080"  # API endpoint (future)
    stdin_open: true
    tty: true
    command: ["python", "-m", "agent.cli"]

  worker:
    build:
      context: .
      dockerfile: docker/worker/Dockerfile
    container_name: doc_worker
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
      ollama:
        condition: service_started
    environment:
      # Database
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-doc}
      DB_PASSWORD: ${DB_PASSWORD:-doc}
      DB_NAME: ${DB_NAME:-docdb}
      # Object storage
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minio}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minio123}
      S3_BUCKET: ${S3_BUCKET:-doc-bucket}
      S3_REGION: ${S3_REGION:-us-east-1}
      # Redis
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_QUEUE_INGEST: ${REDIS_QUEUE_INGEST:-q:ingest}
      REDIS_QUEUE_INDEX: ${REDIS_QUEUE_INDEX:-q:index}
      # Models - Ollama for VLM (math formulas, complex layouts)
      OLLAMA_BASE: ${OLLAMA_BASE:-http://ollama:11434}
      VLM_MODEL: ${VLM_MODEL:-qwen2-vl:7b-instruct-q4_K_M}
      # Embedder (local in-process)
      EMBEDDER_PROVIDER: ${EMBEDDER_PROVIDER:-local}
      EMBEDDER_MODEL: ${EMBEDDER_MODEL:-BAAI/bge-small-en-v1.5}
      EMBEDDER_DEVICE: ${EMBEDDER_DEVICE:-mps}
      EMBEDDER_NORMALIZE: ${EMBEDDER_NORMALIZE:-True}
      # OCR settings
      OCR_ENGINE: ${OCR_ENGINE:-paddleocr}
      OCR_LANG: ${OCR_LANG:-en}
      # Worker settings
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      WORKER_CONCURRENCY: ${WORKER_CONCURRENCY:-2}
    volumes:
      - ./src:/app:cached
      - data:/data
      - models:/root/.cache/huggingface
      - models:/root/.paddleocr                # PaddleOCR model cache
    deploy:
      resources:
        limits:
          cpus: '${WORKER_CPU_LIMIT:-4}'
          memory: ${WORKER_MEMORY_LIMIT:-8G}
    command: ["python", "-m", "agent.worker"]

  notebook:
    image: jupyter/scipy-notebook:latest
    container_name: doc_notebook
    environment:
      JUPYTER_ENABLE_LAB: ${JUPYTER_ENABLE_LAB:-yes}
      GRANT_SUDO: "yes"
      # Database connection for notebooks
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-doc}
      DB_PASSWORD: ${DB_PASSWORD:-doc}
      DB_NAME: ${DB_NAME:-docdb}
      # Object storage
      S3_ENDPOINT: ${S3_ENDPOINT:-http://minio:9000}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY:-minio}
      S3_SECRET_KEY: ${S3_SECRET_KEY:-minio123}
      S3_BUCKET: ${S3_BUCKET:-doc-bucket}
      # Ollama
      OLLAMA_BASE: ${OLLAMA_BASE:-http://ollama:11434}
    ports:
      - "${NOTEBOOK_PORT:-8888}:8888"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./src:/home/jovyan/src:ro              # read-only access to source
      - data:/data
    command: ["start-notebook.sh", "--NotebookApp.token=${JUPYTER_TOKEN:-}"]

volumes:
  pgdata:
    driver: local
  minio-data:
    driver: local
  redis-data:
    driver: local
  models:
    driver: local  # shared cache for Ollama + HF models + PaddleOCR
  data:
    driver: local  # user docs in/out, exports, etc.
